//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class CCameraFollowWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(CCameraFollow), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("SetTrackTagert", SetTrackTagert);
		L.RegFunction("OnTrackTagert", OnTrackTagert);
		L.RegFunction("SetCameraMoveRcet", SetCameraMoveRcet);
		L.RegFunction("ResetCameraPosition", ResetCameraPosition);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetTrackTagert(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			CCameraFollow obj = (CCameraFollow)ToLua.CheckObject<CCameraFollow>(L, 1);
			UnityEngine.Transform arg0 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
			obj.SetTrackTagert(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnTrackTagert(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			CCameraFollow obj = (CCameraFollow)ToLua.CheckObject<CCameraFollow>(L, 1);
			obj.OnTrackTagert();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetCameraMoveRcet(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			CCameraFollow obj = (CCameraFollow)ToLua.CheckObject<CCameraFollow>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
			obj.SetCameraMoveRcet(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ResetCameraPosition(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			CCameraFollow obj = (CCameraFollow)ToLua.CheckObject<CCameraFollow>(L, 1);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
			obj.ResetCameraPosition(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

