//this source code was auto-generated by tolua#, do not modify it
using System;
using System.Collections.Generic;
using LuaInterface;

public class DelegateFactory
{
	public delegate Delegate DelegateCreate(LuaFunction func, LuaTable self, bool flag);
	public static Dictionary<Type, DelegateCreate> dict = new Dictionary<Type, DelegateCreate>();
	static DelegateFactory factory = new DelegateFactory();

	public static void Init()
	{
		Register();
	}

	public static void Register()
	{
		dict.Clear();
		dict.Add(typeof(System.Action), factory.System_Action);
		dict.Add(typeof(UnityEngine.Events.UnityAction), factory.UnityEngine_Events_UnityAction);
		dict.Add(typeof(System.Predicate<int>), factory.System_Predicate_int);
		dict.Add(typeof(System.Action<int>), factory.System_Action_int);
		dict.Add(typeof(System.Comparison<int>), factory.System_Comparison_int);
		dict.Add(typeof(System.Func<int,int>), factory.System_Func_int_int);
		dict.Add(typeof(UnityEngine.Camera.CameraCallback), factory.UnityEngine_Camera_CameraCallback);
		dict.Add(typeof(UnityEngine.Application.LogCallback), factory.UnityEngine_Application_LogCallback);
		dict.Add(typeof(UnityEngine.Application.AdvertisingIdentifierCallback), factory.UnityEngine_Application_AdvertisingIdentifierCallback);
		dict.Add(typeof(UnityEngine.AudioClip.PCMReaderCallback), factory.UnityEngine_AudioClip_PCMReaderCallback);
		dict.Add(typeof(UnityEngine.AudioClip.PCMSetPositionCallback), factory.UnityEngine_AudioClip_PCMSetPositionCallback);
		dict.Add(typeof(UnityEngine.UI.InputField.OnValidateInput), factory.UnityEngine_UI_InputField_OnValidateInput);
		dict.Add(typeof(UnityEngine.Events.UnityAction<bool>), factory.UnityEngine_Events_UnityAction_bool);
		dict.Add(typeof(UnityEngine.Events.UnityAction<UnityEngine.Vector2>), factory.UnityEngine_Events_UnityAction_UnityEngine_Vector2);
		dict.Add(typeof(UnityEngine.Events.UnityAction<float>), factory.UnityEngine_Events_UnityAction_float);
		dict.Add(typeof(System.Predicate<uint>), factory.System_Predicate_uint);
		dict.Add(typeof(System.Action<uint>), factory.System_Action_uint);
		dict.Add(typeof(System.Comparison<uint>), factory.System_Comparison_uint);
		dict.Add(typeof(System.Predicate<UnityEngine.EventSystems.EventTrigger.Entry>), factory.System_Predicate_UnityEngine_EventSystems_EventTrigger_Entry);
		dict.Add(typeof(System.Action<UnityEngine.EventSystems.EventTrigger.Entry>), factory.System_Action_UnityEngine_EventSystems_EventTrigger_Entry);
		dict.Add(typeof(System.Comparison<UnityEngine.EventSystems.EventTrigger.Entry>), factory.System_Comparison_UnityEngine_EventSystems_EventTrigger_Entry);
		dict.Add(typeof(UnityEngine.Events.UnityAction<UnityEngine.EventSystems.BaseEventData>), factory.UnityEngine_Events_UnityAction_UnityEngine_EventSystems_BaseEventData);
		dict.Add(typeof(UnityEngine.RectTransform.ReapplyDrivenProperties), factory.UnityEngine_RectTransform_ReapplyDrivenProperties);
		dict.Add(typeof(UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.LoadSceneMode>), factory.UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode);
		dict.Add(typeof(UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene>), factory.UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene);
		dict.Add(typeof(UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.Scene>), factory.UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene);
		dict.Add(typeof(UnityEngine.Canvas.WillRenderCanvases), factory.UnityEngine_Canvas_WillRenderCanvases);
		dict.Add(typeof(OnServerConnect), factory.OnServerConnect);
		dict.Add(typeof(OnServerCloseConnect), factory.OnServerCloseConnect);
		dict.Add(typeof(OnServerMessage), factory.OnServerMessage);
		dict.Add(typeof(OnHeroStarMove), factory.OnHeroStarMove);
		dict.Add(typeof(OnHeroEndMove), factory.OnHeroEndMove);
		dict.Add(typeof(OnHeroMoveIng), factory.OnHeroMoveIng);
		dict.Add(typeof(OnHeroClickEntity), factory.OnHeroClickEntity);
		dict.Add(typeof(OnHeroClickGround), factory.OnHeroClickGround);
		dict.Add(typeof(OnAttackKeyFrame), factory.OnAttackKeyFrame);
		dict.Add(typeof(OnAttackEnd), factory.OnAttackEnd);
		dict.Add(typeof(OnBeatKeyFrame), factory.OnBeatKeyFrame);
		dict.Add(typeof(OnBeatEnd), factory.OnBeatEnd);
		dict.Add(typeof(OnDeadEnd), factory.OnDeadEnd);
		dict.Add(typeof(OnMoveTargetCallBack), factory.OnMoveTargetCallBack);
		dict.Add(typeof(OnSkillEnd), factory.OnSkillEnd);
		dict.Add(typeof(OnSkillKeyFrame), factory.OnSkillKeyFrame);
		dict.Add(typeof(OnSkillTriggerHitEffect), factory.OnSkillTriggerHitEffect);
		dict.Add(typeof(System.Action<UnityEngine.Object>), factory.System_Action_UnityEngine_Object);
		dict.Add(typeof(OnDragBegin), factory.OnDragBegin);
		dict.Add(typeof(OnDrag), factory.OnDrag);
		dict.Add(typeof(OnDragEnd), factory.OnDragEnd);
		dict.Add(typeof(OnFuncCallBackDelegate), factory.OnFuncCallBackDelegate);

		DelegateTraits<System.Action>.Init(factory.System_Action);
		DelegateTraits<UnityEngine.Events.UnityAction>.Init(factory.UnityEngine_Events_UnityAction);
		DelegateTraits<System.Predicate<int>>.Init(factory.System_Predicate_int);
		DelegateTraits<System.Action<int>>.Init(factory.System_Action_int);
		DelegateTraits<System.Comparison<int>>.Init(factory.System_Comparison_int);
		DelegateTraits<System.Func<int,int>>.Init(factory.System_Func_int_int);
		DelegateTraits<UnityEngine.Camera.CameraCallback>.Init(factory.UnityEngine_Camera_CameraCallback);
		DelegateTraits<UnityEngine.Application.LogCallback>.Init(factory.UnityEngine_Application_LogCallback);
		DelegateTraits<UnityEngine.Application.AdvertisingIdentifierCallback>.Init(factory.UnityEngine_Application_AdvertisingIdentifierCallback);
		DelegateTraits<UnityEngine.AudioClip.PCMReaderCallback>.Init(factory.UnityEngine_AudioClip_PCMReaderCallback);
		DelegateTraits<UnityEngine.AudioClip.PCMSetPositionCallback>.Init(factory.UnityEngine_AudioClip_PCMSetPositionCallback);
		DelegateTraits<UnityEngine.UI.InputField.OnValidateInput>.Init(factory.UnityEngine_UI_InputField_OnValidateInput);
		DelegateTraits<UnityEngine.Events.UnityAction<bool>>.Init(factory.UnityEngine_Events_UnityAction_bool);
		DelegateTraits<UnityEngine.Events.UnityAction<UnityEngine.Vector2>>.Init(factory.UnityEngine_Events_UnityAction_UnityEngine_Vector2);
		DelegateTraits<UnityEngine.Events.UnityAction<float>>.Init(factory.UnityEngine_Events_UnityAction_float);
		DelegateTraits<System.Predicate<uint>>.Init(factory.System_Predicate_uint);
		DelegateTraits<System.Action<uint>>.Init(factory.System_Action_uint);
		DelegateTraits<System.Comparison<uint>>.Init(factory.System_Comparison_uint);
		DelegateTraits<System.Predicate<UnityEngine.EventSystems.EventTrigger.Entry>>.Init(factory.System_Predicate_UnityEngine_EventSystems_EventTrigger_Entry);
		DelegateTraits<System.Action<UnityEngine.EventSystems.EventTrigger.Entry>>.Init(factory.System_Action_UnityEngine_EventSystems_EventTrigger_Entry);
		DelegateTraits<System.Comparison<UnityEngine.EventSystems.EventTrigger.Entry>>.Init(factory.System_Comparison_UnityEngine_EventSystems_EventTrigger_Entry);
		DelegateTraits<UnityEngine.Events.UnityAction<UnityEngine.EventSystems.BaseEventData>>.Init(factory.UnityEngine_Events_UnityAction_UnityEngine_EventSystems_BaseEventData);
		DelegateTraits<UnityEngine.RectTransform.ReapplyDrivenProperties>.Init(factory.UnityEngine_RectTransform_ReapplyDrivenProperties);
		DelegateTraits<UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.LoadSceneMode>>.Init(factory.UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode);
		DelegateTraits<UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene>>.Init(factory.UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene);
		DelegateTraits<UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.Scene>>.Init(factory.UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene);
		DelegateTraits<UnityEngine.Canvas.WillRenderCanvases>.Init(factory.UnityEngine_Canvas_WillRenderCanvases);
		DelegateTraits<OnServerConnect>.Init(factory.OnServerConnect);
		DelegateTraits<OnServerCloseConnect>.Init(factory.OnServerCloseConnect);
		DelegateTraits<OnServerMessage>.Init(factory.OnServerMessage);
		DelegateTraits<OnHeroStarMove>.Init(factory.OnHeroStarMove);
		DelegateTraits<OnHeroEndMove>.Init(factory.OnHeroEndMove);
		DelegateTraits<OnHeroMoveIng>.Init(factory.OnHeroMoveIng);
		DelegateTraits<OnHeroClickEntity>.Init(factory.OnHeroClickEntity);
		DelegateTraits<OnHeroClickGround>.Init(factory.OnHeroClickGround);
		DelegateTraits<OnAttackKeyFrame>.Init(factory.OnAttackKeyFrame);
		DelegateTraits<OnAttackEnd>.Init(factory.OnAttackEnd);
		DelegateTraits<OnBeatKeyFrame>.Init(factory.OnBeatKeyFrame);
		DelegateTraits<OnBeatEnd>.Init(factory.OnBeatEnd);
		DelegateTraits<OnDeadEnd>.Init(factory.OnDeadEnd);
		DelegateTraits<OnMoveTargetCallBack>.Init(factory.OnMoveTargetCallBack);
		DelegateTraits<OnSkillEnd>.Init(factory.OnSkillEnd);
		DelegateTraits<OnSkillKeyFrame>.Init(factory.OnSkillKeyFrame);
		DelegateTraits<OnSkillTriggerHitEffect>.Init(factory.OnSkillTriggerHitEffect);
		DelegateTraits<System.Action<UnityEngine.Object>>.Init(factory.System_Action_UnityEngine_Object);
		DelegateTraits<OnDragBegin>.Init(factory.OnDragBegin);
		DelegateTraits<OnDrag>.Init(factory.OnDrag);
		DelegateTraits<OnDragEnd>.Init(factory.OnDragEnd);
		DelegateTraits<OnFuncCallBackDelegate>.Init(factory.OnFuncCallBackDelegate);

		TypeTraits<System.Action>.Init(factory.Check_System_Action);
		TypeTraits<UnityEngine.Events.UnityAction>.Init(factory.Check_UnityEngine_Events_UnityAction);
		TypeTraits<System.Predicate<int>>.Init(factory.Check_System_Predicate_int);
		TypeTraits<System.Action<int>>.Init(factory.Check_System_Action_int);
		TypeTraits<System.Comparison<int>>.Init(factory.Check_System_Comparison_int);
		TypeTraits<System.Func<int,int>>.Init(factory.Check_System_Func_int_int);
		TypeTraits<UnityEngine.Camera.CameraCallback>.Init(factory.Check_UnityEngine_Camera_CameraCallback);
		TypeTraits<UnityEngine.Application.LogCallback>.Init(factory.Check_UnityEngine_Application_LogCallback);
		TypeTraits<UnityEngine.Application.AdvertisingIdentifierCallback>.Init(factory.Check_UnityEngine_Application_AdvertisingIdentifierCallback);
		TypeTraits<UnityEngine.AudioClip.PCMReaderCallback>.Init(factory.Check_UnityEngine_AudioClip_PCMReaderCallback);
		TypeTraits<UnityEngine.AudioClip.PCMSetPositionCallback>.Init(factory.Check_UnityEngine_AudioClip_PCMSetPositionCallback);
		TypeTraits<UnityEngine.UI.InputField.OnValidateInput>.Init(factory.Check_UnityEngine_UI_InputField_OnValidateInput);
		TypeTraits<UnityEngine.Events.UnityAction<bool>>.Init(factory.Check_UnityEngine_Events_UnityAction_bool);
		TypeTraits<UnityEngine.Events.UnityAction<UnityEngine.Vector2>>.Init(factory.Check_UnityEngine_Events_UnityAction_UnityEngine_Vector2);
		TypeTraits<UnityEngine.Events.UnityAction<float>>.Init(factory.Check_UnityEngine_Events_UnityAction_float);
		TypeTraits<System.Predicate<uint>>.Init(factory.Check_System_Predicate_uint);
		TypeTraits<System.Action<uint>>.Init(factory.Check_System_Action_uint);
		TypeTraits<System.Comparison<uint>>.Init(factory.Check_System_Comparison_uint);
		TypeTraits<System.Predicate<UnityEngine.EventSystems.EventTrigger.Entry>>.Init(factory.Check_System_Predicate_UnityEngine_EventSystems_EventTrigger_Entry);
		TypeTraits<System.Action<UnityEngine.EventSystems.EventTrigger.Entry>>.Init(factory.Check_System_Action_UnityEngine_EventSystems_EventTrigger_Entry);
		TypeTraits<System.Comparison<UnityEngine.EventSystems.EventTrigger.Entry>>.Init(factory.Check_System_Comparison_UnityEngine_EventSystems_EventTrigger_Entry);
		TypeTraits<UnityEngine.Events.UnityAction<UnityEngine.EventSystems.BaseEventData>>.Init(factory.Check_UnityEngine_Events_UnityAction_UnityEngine_EventSystems_BaseEventData);
		TypeTraits<UnityEngine.RectTransform.ReapplyDrivenProperties>.Init(factory.Check_UnityEngine_RectTransform_ReapplyDrivenProperties);
		TypeTraits<UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.LoadSceneMode>>.Init(factory.Check_UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode);
		TypeTraits<UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene>>.Init(factory.Check_UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene);
		TypeTraits<UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.Scene>>.Init(factory.Check_UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene);
		TypeTraits<UnityEngine.Canvas.WillRenderCanvases>.Init(factory.Check_UnityEngine_Canvas_WillRenderCanvases);
		TypeTraits<OnServerConnect>.Init(factory.Check_OnServerConnect);
		TypeTraits<OnServerCloseConnect>.Init(factory.Check_OnServerCloseConnect);
		TypeTraits<OnServerMessage>.Init(factory.Check_OnServerMessage);
		TypeTraits<OnHeroStarMove>.Init(factory.Check_OnHeroStarMove);
		TypeTraits<OnHeroEndMove>.Init(factory.Check_OnHeroEndMove);
		TypeTraits<OnHeroMoveIng>.Init(factory.Check_OnHeroMoveIng);
		TypeTraits<OnHeroClickEntity>.Init(factory.Check_OnHeroClickEntity);
		TypeTraits<OnHeroClickGround>.Init(factory.Check_OnHeroClickGround);
		TypeTraits<OnAttackKeyFrame>.Init(factory.Check_OnAttackKeyFrame);
		TypeTraits<OnAttackEnd>.Init(factory.Check_OnAttackEnd);
		TypeTraits<OnBeatKeyFrame>.Init(factory.Check_OnBeatKeyFrame);
		TypeTraits<OnBeatEnd>.Init(factory.Check_OnBeatEnd);
		TypeTraits<OnDeadEnd>.Init(factory.Check_OnDeadEnd);
		TypeTraits<OnMoveTargetCallBack>.Init(factory.Check_OnMoveTargetCallBack);
		TypeTraits<OnSkillEnd>.Init(factory.Check_OnSkillEnd);
		TypeTraits<OnSkillKeyFrame>.Init(factory.Check_OnSkillKeyFrame);
		TypeTraits<OnSkillTriggerHitEffect>.Init(factory.Check_OnSkillTriggerHitEffect);
		TypeTraits<System.Action<UnityEngine.Object>>.Init(factory.Check_System_Action_UnityEngine_Object);
		TypeTraits<OnDragBegin>.Init(factory.Check_OnDragBegin);
		TypeTraits<OnDrag>.Init(factory.Check_OnDrag);
		TypeTraits<OnDragEnd>.Init(factory.Check_OnDragEnd);
		TypeTraits<OnFuncCallBackDelegate>.Init(factory.Check_OnFuncCallBackDelegate);

		StackTraits<System.Action>.Push = factory.Push_System_Action;
		StackTraits<UnityEngine.Events.UnityAction>.Push = factory.Push_UnityEngine_Events_UnityAction;
		StackTraits<System.Predicate<int>>.Push = factory.Push_System_Predicate_int;
		StackTraits<System.Action<int>>.Push = factory.Push_System_Action_int;
		StackTraits<System.Comparison<int>>.Push = factory.Push_System_Comparison_int;
		StackTraits<System.Func<int,int>>.Push = factory.Push_System_Func_int_int;
		StackTraits<UnityEngine.Camera.CameraCallback>.Push = factory.Push_UnityEngine_Camera_CameraCallback;
		StackTraits<UnityEngine.Application.LogCallback>.Push = factory.Push_UnityEngine_Application_LogCallback;
		StackTraits<UnityEngine.Application.AdvertisingIdentifierCallback>.Push = factory.Push_UnityEngine_Application_AdvertisingIdentifierCallback;
		StackTraits<UnityEngine.AudioClip.PCMReaderCallback>.Push = factory.Push_UnityEngine_AudioClip_PCMReaderCallback;
		StackTraits<UnityEngine.AudioClip.PCMSetPositionCallback>.Push = factory.Push_UnityEngine_AudioClip_PCMSetPositionCallback;
		StackTraits<UnityEngine.UI.InputField.OnValidateInput>.Push = factory.Push_UnityEngine_UI_InputField_OnValidateInput;
		StackTraits<UnityEngine.Events.UnityAction<bool>>.Push = factory.Push_UnityEngine_Events_UnityAction_bool;
		StackTraits<UnityEngine.Events.UnityAction<UnityEngine.Vector2>>.Push = factory.Push_UnityEngine_Events_UnityAction_UnityEngine_Vector2;
		StackTraits<UnityEngine.Events.UnityAction<float>>.Push = factory.Push_UnityEngine_Events_UnityAction_float;
		StackTraits<System.Predicate<uint>>.Push = factory.Push_System_Predicate_uint;
		StackTraits<System.Action<uint>>.Push = factory.Push_System_Action_uint;
		StackTraits<System.Comparison<uint>>.Push = factory.Push_System_Comparison_uint;
		StackTraits<System.Predicate<UnityEngine.EventSystems.EventTrigger.Entry>>.Push = factory.Push_System_Predicate_UnityEngine_EventSystems_EventTrigger_Entry;
		StackTraits<System.Action<UnityEngine.EventSystems.EventTrigger.Entry>>.Push = factory.Push_System_Action_UnityEngine_EventSystems_EventTrigger_Entry;
		StackTraits<System.Comparison<UnityEngine.EventSystems.EventTrigger.Entry>>.Push = factory.Push_System_Comparison_UnityEngine_EventSystems_EventTrigger_Entry;
		StackTraits<UnityEngine.Events.UnityAction<UnityEngine.EventSystems.BaseEventData>>.Push = factory.Push_UnityEngine_Events_UnityAction_UnityEngine_EventSystems_BaseEventData;
		StackTraits<UnityEngine.RectTransform.ReapplyDrivenProperties>.Push = factory.Push_UnityEngine_RectTransform_ReapplyDrivenProperties;
		StackTraits<UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.LoadSceneMode>>.Push = factory.Push_UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode;
		StackTraits<UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene>>.Push = factory.Push_UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene;
		StackTraits<UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.Scene>>.Push = factory.Push_UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene;
		StackTraits<UnityEngine.Canvas.WillRenderCanvases>.Push = factory.Push_UnityEngine_Canvas_WillRenderCanvases;
		StackTraits<OnServerConnect>.Push = factory.Push_OnServerConnect;
		StackTraits<OnServerCloseConnect>.Push = factory.Push_OnServerCloseConnect;
		StackTraits<OnServerMessage>.Push = factory.Push_OnServerMessage;
		StackTraits<OnHeroStarMove>.Push = factory.Push_OnHeroStarMove;
		StackTraits<OnHeroEndMove>.Push = factory.Push_OnHeroEndMove;
		StackTraits<OnHeroMoveIng>.Push = factory.Push_OnHeroMoveIng;
		StackTraits<OnHeroClickEntity>.Push = factory.Push_OnHeroClickEntity;
		StackTraits<OnHeroClickGround>.Push = factory.Push_OnHeroClickGround;
		StackTraits<OnAttackKeyFrame>.Push = factory.Push_OnAttackKeyFrame;
		StackTraits<OnAttackEnd>.Push = factory.Push_OnAttackEnd;
		StackTraits<OnBeatKeyFrame>.Push = factory.Push_OnBeatKeyFrame;
		StackTraits<OnBeatEnd>.Push = factory.Push_OnBeatEnd;
		StackTraits<OnDeadEnd>.Push = factory.Push_OnDeadEnd;
		StackTraits<OnMoveTargetCallBack>.Push = factory.Push_OnMoveTargetCallBack;
		StackTraits<OnSkillEnd>.Push = factory.Push_OnSkillEnd;
		StackTraits<OnSkillKeyFrame>.Push = factory.Push_OnSkillKeyFrame;
		StackTraits<OnSkillTriggerHitEffect>.Push = factory.Push_OnSkillTriggerHitEffect;
		StackTraits<System.Action<UnityEngine.Object>>.Push = factory.Push_System_Action_UnityEngine_Object;
		StackTraits<OnDragBegin>.Push = factory.Push_OnDragBegin;
		StackTraits<OnDrag>.Push = factory.Push_OnDrag;
		StackTraits<OnDragEnd>.Push = factory.Push_OnDragEnd;
		StackTraits<OnFuncCallBackDelegate>.Push = factory.Push_OnFuncCallBackDelegate;
	}
    
    public static Delegate CreateDelegate(Type t, LuaFunction func = null)
    {
        DelegateCreate Create = null;

        if (!dict.TryGetValue(t, out Create))
        {
            throw new LuaException(string.Format("Delegate {0} not register", LuaMisc.GetTypeName(t)));            
        }

        if (func != null)
        {
            LuaState state = func.GetLuaState();
            LuaDelegate target = state.GetLuaDelegate(func);
            
            if (target != null)
            {
                return Delegate.CreateDelegate(t, target, target.method);
            }  
            else
            {
                Delegate d = Create(func, null, false);
                target = d.Target as LuaDelegate;
                state.AddLuaDelegate(target, func);
                return d;
            }       
        }

        return Create(null, null, false);        
    }
    
    public static Delegate CreateDelegate(Type t, LuaFunction func, LuaTable self)
    {
        DelegateCreate Create = null;

        if (!dict.TryGetValue(t, out Create))
        {
            throw new LuaException(string.Format("Delegate {0} not register", LuaMisc.GetTypeName(t)));
        }

        if (func != null)
        {
            LuaState state = func.GetLuaState();
            LuaDelegate target = state.GetLuaDelegate(func, self);

            if (target != null)
            {
                return Delegate.CreateDelegate(t, target, target.method);
            }
            else
            {
                Delegate d = Create(func, self, true);
                target = d.Target as LuaDelegate;
                state.AddLuaDelegate(target, func, self);
                return d;
            }
        }

        return Create(null, null, true);
    }
    
    public static Delegate RemoveDelegate(Delegate obj, LuaFunction func)
    {
        LuaState state = func.GetLuaState();
        Delegate[] ds = obj.GetInvocationList();

        for (int i = 0; i < ds.Length; i++)
        {
            LuaDelegate ld = ds[i].Target as LuaDelegate;

            if (ld != null && ld.func == func)
            {
                obj = Delegate.Remove(obj, ds[i]);
                state.DelayDispose(ld.func);
                break;
            }
        }

        return obj;
    }
    
    public static Delegate RemoveDelegate(Delegate obj, Delegate dg)
    {
        LuaDelegate remove = dg.Target as LuaDelegate;

        if (remove == null)
        {
            obj = Delegate.Remove(obj, dg);
            return obj;
        }

        LuaState state = remove.func.GetLuaState();
        Delegate[] ds = obj.GetInvocationList();        

        for (int i = 0; i < ds.Length; i++)
        {
            LuaDelegate ld = ds[i].Target as LuaDelegate;

            if (ld != null && ld == remove)
            {
                obj = Delegate.Remove(obj, ds[i]);
                state.DelayDispose(ld.func);
                state.DelayDispose(ld.self);
                break;
            }
        }

        return obj;
    }

	class System_Action_Event : LuaDelegate
	{
		public System_Action_Event(LuaFunction func) : base(func) { }
		public System_Action_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public System.Action System_Action(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			System_Action_Event target = new System_Action_Event(func);
			System.Action d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_Event target = new System_Action_Event(func, self);
			System.Action d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Action(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(System.Action), L, pos);
	}

	void Push_System_Action(IntPtr L, System.Action o)
	{
		ToLua.Push(L, o);
	}

	class UnityEngine_Events_UnityAction_Event : LuaDelegate
	{
		public UnityEngine_Events_UnityAction_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Events_UnityAction_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public UnityEngine.Events.UnityAction UnityEngine_Events_UnityAction(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Events.UnityAction fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Events_UnityAction_Event target = new UnityEngine_Events_UnityAction_Event(func);
			UnityEngine.Events.UnityAction d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Events_UnityAction_Event target = new UnityEngine_Events_UnityAction_Event(func, self);
			UnityEngine.Events.UnityAction d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_UnityEngine_Events_UnityAction(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(UnityEngine.Events.UnityAction), L, pos);
	}

	void Push_UnityEngine_Events_UnityAction(IntPtr L, UnityEngine.Events.UnityAction o)
	{
		ToLua.Push(L, o);
	}

	class System_Predicate_int_Event : LuaDelegate
	{
		public System_Predicate_int_Event(LuaFunction func) : base(func) { }
		public System_Predicate_int_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public bool Call(int param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}

		public bool CallWithSelf(int param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}
	}

	public System.Predicate<int> System_Predicate_int(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Predicate<int> fn = delegate(int param0) { return false; };
			return fn;
		}

		if(!flag)
		{
			System_Predicate_int_Event target = new System_Predicate_int_Event(func);
			System.Predicate<int> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Predicate_int_Event target = new System_Predicate_int_Event(func, self);
			System.Predicate<int> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Predicate_int(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(System.Predicate<int>), L, pos);
	}

	void Push_System_Predicate_int(IntPtr L, System.Predicate<int> o)
	{
		ToLua.Push(L, o);
	}

	class System_Action_int_Event : LuaDelegate
	{
		public System_Action_int_Event(LuaFunction func) : base(func) { }
		public System_Action_int_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(int param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(int param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public System.Action<int> System_Action_int(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<int> fn = delegate(int param0) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_int_Event target = new System_Action_int_Event(func);
			System.Action<int> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_int_Event target = new System_Action_int_Event(func, self);
			System.Action<int> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Action_int(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(System.Action<int>), L, pos);
	}

	void Push_System_Action_int(IntPtr L, System.Action<int> o)
	{
		ToLua.Push(L, o);
	}

	class System_Comparison_int_Event : LuaDelegate
	{
		public System_Comparison_int_Event(LuaFunction func) : base(func) { }
		public System_Comparison_int_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public int Call(int param0, int param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			int ret = (int)func.CheckNumber();
			func.EndPCall();
			return ret;
		}

		public int CallWithSelf(int param0, int param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			int ret = (int)func.CheckNumber();
			func.EndPCall();
			return ret;
		}
	}

	public System.Comparison<int> System_Comparison_int(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Comparison<int> fn = delegate(int param0, int param1) { return 0; };
			return fn;
		}

		if(!flag)
		{
			System_Comparison_int_Event target = new System_Comparison_int_Event(func);
			System.Comparison<int> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Comparison_int_Event target = new System_Comparison_int_Event(func, self);
			System.Comparison<int> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Comparison_int(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(System.Comparison<int>), L, pos);
	}

	void Push_System_Comparison_int(IntPtr L, System.Comparison<int> o)
	{
		ToLua.Push(L, o);
	}

	class System_Func_int_int_Event : LuaDelegate
	{
		public System_Func_int_int_Event(LuaFunction func) : base(func) { }
		public System_Func_int_int_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public int Call(int param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			int ret = (int)func.CheckNumber();
			func.EndPCall();
			return ret;
		}

		public int CallWithSelf(int param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			int ret = (int)func.CheckNumber();
			func.EndPCall();
			return ret;
		}
	}

	public System.Func<int,int> System_Func_int_int(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Func<int,int> fn = delegate(int param0) { return 0; };
			return fn;
		}

		if(!flag)
		{
			System_Func_int_int_Event target = new System_Func_int_int_Event(func);
			System.Func<int,int> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Func_int_int_Event target = new System_Func_int_int_Event(func, self);
			System.Func<int,int> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Func_int_int(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(System.Func<int,int>), L, pos);
	}

	void Push_System_Func_int_int(IntPtr L, System.Func<int,int> o)
	{
		ToLua.Push(L, o);
	}

	class UnityEngine_Camera_CameraCallback_Event : LuaDelegate
	{
		public UnityEngine_Camera_CameraCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Camera_CameraCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.Camera param0)
		{
			func.BeginPCall();
			func.PushSealed(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.Camera param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushSealed(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public UnityEngine.Camera.CameraCallback UnityEngine_Camera_CameraCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Camera.CameraCallback fn = delegate(UnityEngine.Camera param0) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Camera_CameraCallback_Event target = new UnityEngine_Camera_CameraCallback_Event(func);
			UnityEngine.Camera.CameraCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Camera_CameraCallback_Event target = new UnityEngine_Camera_CameraCallback_Event(func, self);
			UnityEngine.Camera.CameraCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_UnityEngine_Camera_CameraCallback(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(UnityEngine.Camera.CameraCallback), L, pos);
	}

	void Push_UnityEngine_Camera_CameraCallback(IntPtr L, UnityEngine.Camera.CameraCallback o)
	{
		ToLua.Push(L, o);
	}

	class UnityEngine_Application_LogCallback_Event : LuaDelegate
	{
		public UnityEngine_Application_LogCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Application_LogCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(string param0, string param1, UnityEngine.LogType param2)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(string param0, string param1, UnityEngine.LogType param2)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}
	}

	public UnityEngine.Application.LogCallback UnityEngine_Application_LogCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Application.LogCallback fn = delegate(string param0, string param1, UnityEngine.LogType param2) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Application_LogCallback_Event target = new UnityEngine_Application_LogCallback_Event(func);
			UnityEngine.Application.LogCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Application_LogCallback_Event target = new UnityEngine_Application_LogCallback_Event(func, self);
			UnityEngine.Application.LogCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_UnityEngine_Application_LogCallback(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(UnityEngine.Application.LogCallback), L, pos);
	}

	void Push_UnityEngine_Application_LogCallback(IntPtr L, UnityEngine.Application.LogCallback o)
	{
		ToLua.Push(L, o);
	}

	class UnityEngine_Application_AdvertisingIdentifierCallback_Event : LuaDelegate
	{
		public UnityEngine_Application_AdvertisingIdentifierCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Application_AdvertisingIdentifierCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(string param0, bool param1, string param2)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(string param0, bool param1, string param2)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}
	}

	public UnityEngine.Application.AdvertisingIdentifierCallback UnityEngine_Application_AdvertisingIdentifierCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Application.AdvertisingIdentifierCallback fn = delegate(string param0, bool param1, string param2) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Application_AdvertisingIdentifierCallback_Event target = new UnityEngine_Application_AdvertisingIdentifierCallback_Event(func);
			UnityEngine.Application.AdvertisingIdentifierCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Application_AdvertisingIdentifierCallback_Event target = new UnityEngine_Application_AdvertisingIdentifierCallback_Event(func, self);
			UnityEngine.Application.AdvertisingIdentifierCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_UnityEngine_Application_AdvertisingIdentifierCallback(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(UnityEngine.Application.AdvertisingIdentifierCallback), L, pos);
	}

	void Push_UnityEngine_Application_AdvertisingIdentifierCallback(IntPtr L, UnityEngine.Application.AdvertisingIdentifierCallback o)
	{
		ToLua.Push(L, o);
	}

	class UnityEngine_AudioClip_PCMReaderCallback_Event : LuaDelegate
	{
		public UnityEngine_AudioClip_PCMReaderCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_AudioClip_PCMReaderCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(float[] param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(float[] param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public UnityEngine.AudioClip.PCMReaderCallback UnityEngine_AudioClip_PCMReaderCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.AudioClip.PCMReaderCallback fn = delegate(float[] param0) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_AudioClip_PCMReaderCallback_Event target = new UnityEngine_AudioClip_PCMReaderCallback_Event(func);
			UnityEngine.AudioClip.PCMReaderCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_AudioClip_PCMReaderCallback_Event target = new UnityEngine_AudioClip_PCMReaderCallback_Event(func, self);
			UnityEngine.AudioClip.PCMReaderCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_UnityEngine_AudioClip_PCMReaderCallback(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(UnityEngine.AudioClip.PCMReaderCallback), L, pos);
	}

	void Push_UnityEngine_AudioClip_PCMReaderCallback(IntPtr L, UnityEngine.AudioClip.PCMReaderCallback o)
	{
		ToLua.Push(L, o);
	}

	class UnityEngine_AudioClip_PCMSetPositionCallback_Event : LuaDelegate
	{
		public UnityEngine_AudioClip_PCMSetPositionCallback_Event(LuaFunction func) : base(func) { }
		public UnityEngine_AudioClip_PCMSetPositionCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(int param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(int param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public UnityEngine.AudioClip.PCMSetPositionCallback UnityEngine_AudioClip_PCMSetPositionCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.AudioClip.PCMSetPositionCallback fn = delegate(int param0) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_AudioClip_PCMSetPositionCallback_Event target = new UnityEngine_AudioClip_PCMSetPositionCallback_Event(func);
			UnityEngine.AudioClip.PCMSetPositionCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_AudioClip_PCMSetPositionCallback_Event target = new UnityEngine_AudioClip_PCMSetPositionCallback_Event(func, self);
			UnityEngine.AudioClip.PCMSetPositionCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_UnityEngine_AudioClip_PCMSetPositionCallback(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(UnityEngine.AudioClip.PCMSetPositionCallback), L, pos);
	}

	void Push_UnityEngine_AudioClip_PCMSetPositionCallback(IntPtr L, UnityEngine.AudioClip.PCMSetPositionCallback o)
	{
		ToLua.Push(L, o);
	}

	class UnityEngine_UI_InputField_OnValidateInput_Event : LuaDelegate
	{
		public UnityEngine_UI_InputField_OnValidateInput_Event(LuaFunction func) : base(func) { }
		public UnityEngine_UI_InputField_OnValidateInput_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public char Call(string param0, int param1, char param2)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			char ret = (char)func.CheckNumber();
			func.EndPCall();
			return ret;
		}

		public char CallWithSelf(string param0, int param1, char param2)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			char ret = (char)func.CheckNumber();
			func.EndPCall();
			return ret;
		}
	}

	public UnityEngine.UI.InputField.OnValidateInput UnityEngine_UI_InputField_OnValidateInput(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.UI.InputField.OnValidateInput fn = delegate(string param0, int param1, char param2) { return '\0'; };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_UI_InputField_OnValidateInput_Event target = new UnityEngine_UI_InputField_OnValidateInput_Event(func);
			UnityEngine.UI.InputField.OnValidateInput d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_UI_InputField_OnValidateInput_Event target = new UnityEngine_UI_InputField_OnValidateInput_Event(func, self);
			UnityEngine.UI.InputField.OnValidateInput d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_UnityEngine_UI_InputField_OnValidateInput(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(UnityEngine.UI.InputField.OnValidateInput), L, pos);
	}

	void Push_UnityEngine_UI_InputField_OnValidateInput(IntPtr L, UnityEngine.UI.InputField.OnValidateInput o)
	{
		ToLua.Push(L, o);
	}

	class UnityEngine_Events_UnityAction_bool_Event : LuaDelegate
	{
		public UnityEngine_Events_UnityAction_bool_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Events_UnityAction_bool_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(bool param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(bool param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public UnityEngine.Events.UnityAction<bool> UnityEngine_Events_UnityAction_bool(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Events.UnityAction<bool> fn = delegate(bool param0) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Events_UnityAction_bool_Event target = new UnityEngine_Events_UnityAction_bool_Event(func);
			UnityEngine.Events.UnityAction<bool> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Events_UnityAction_bool_Event target = new UnityEngine_Events_UnityAction_bool_Event(func, self);
			UnityEngine.Events.UnityAction<bool> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_UnityEngine_Events_UnityAction_bool(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(UnityEngine.Events.UnityAction<bool>), L, pos);
	}

	void Push_UnityEngine_Events_UnityAction_bool(IntPtr L, UnityEngine.Events.UnityAction<bool> o)
	{
		ToLua.Push(L, o);
	}

	class UnityEngine_Events_UnityAction_UnityEngine_Vector2_Event : LuaDelegate
	{
		public UnityEngine_Events_UnityAction_UnityEngine_Vector2_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Events_UnityAction_UnityEngine_Vector2_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.Vector2 param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.Vector2 param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public UnityEngine.Events.UnityAction<UnityEngine.Vector2> UnityEngine_Events_UnityAction_UnityEngine_Vector2(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Events.UnityAction<UnityEngine.Vector2> fn = delegate(UnityEngine.Vector2 param0) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Events_UnityAction_UnityEngine_Vector2_Event target = new UnityEngine_Events_UnityAction_UnityEngine_Vector2_Event(func);
			UnityEngine.Events.UnityAction<UnityEngine.Vector2> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Events_UnityAction_UnityEngine_Vector2_Event target = new UnityEngine_Events_UnityAction_UnityEngine_Vector2_Event(func, self);
			UnityEngine.Events.UnityAction<UnityEngine.Vector2> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_UnityEngine_Events_UnityAction_UnityEngine_Vector2(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(UnityEngine.Events.UnityAction<UnityEngine.Vector2>), L, pos);
	}

	void Push_UnityEngine_Events_UnityAction_UnityEngine_Vector2(IntPtr L, UnityEngine.Events.UnityAction<UnityEngine.Vector2> o)
	{
		ToLua.Push(L, o);
	}

	class UnityEngine_Events_UnityAction_float_Event : LuaDelegate
	{
		public UnityEngine_Events_UnityAction_float_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Events_UnityAction_float_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(float param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(float param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public UnityEngine.Events.UnityAction<float> UnityEngine_Events_UnityAction_float(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Events.UnityAction<float> fn = delegate(float param0) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Events_UnityAction_float_Event target = new UnityEngine_Events_UnityAction_float_Event(func);
			UnityEngine.Events.UnityAction<float> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Events_UnityAction_float_Event target = new UnityEngine_Events_UnityAction_float_Event(func, self);
			UnityEngine.Events.UnityAction<float> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_UnityEngine_Events_UnityAction_float(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(UnityEngine.Events.UnityAction<float>), L, pos);
	}

	void Push_UnityEngine_Events_UnityAction_float(IntPtr L, UnityEngine.Events.UnityAction<float> o)
	{
		ToLua.Push(L, o);
	}

	class System_Predicate_uint_Event : LuaDelegate
	{
		public System_Predicate_uint_Event(LuaFunction func) : base(func) { }
		public System_Predicate_uint_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public bool Call(uint param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}

		public bool CallWithSelf(uint param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}
	}

	public System.Predicate<uint> System_Predicate_uint(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Predicate<uint> fn = delegate(uint param0) { return false; };
			return fn;
		}

		if(!flag)
		{
			System_Predicate_uint_Event target = new System_Predicate_uint_Event(func);
			System.Predicate<uint> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Predicate_uint_Event target = new System_Predicate_uint_Event(func, self);
			System.Predicate<uint> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Predicate_uint(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(System.Predicate<uint>), L, pos);
	}

	void Push_System_Predicate_uint(IntPtr L, System.Predicate<uint> o)
	{
		ToLua.Push(L, o);
	}

	class System_Action_uint_Event : LuaDelegate
	{
		public System_Action_uint_Event(LuaFunction func) : base(func) { }
		public System_Action_uint_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(uint param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(uint param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public System.Action<uint> System_Action_uint(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<uint> fn = delegate(uint param0) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_uint_Event target = new System_Action_uint_Event(func);
			System.Action<uint> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_uint_Event target = new System_Action_uint_Event(func, self);
			System.Action<uint> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Action_uint(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(System.Action<uint>), L, pos);
	}

	void Push_System_Action_uint(IntPtr L, System.Action<uint> o)
	{
		ToLua.Push(L, o);
	}

	class System_Comparison_uint_Event : LuaDelegate
	{
		public System_Comparison_uint_Event(LuaFunction func) : base(func) { }
		public System_Comparison_uint_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public int Call(uint param0, uint param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			int ret = (int)func.CheckNumber();
			func.EndPCall();
			return ret;
		}

		public int CallWithSelf(uint param0, uint param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			int ret = (int)func.CheckNumber();
			func.EndPCall();
			return ret;
		}
	}

	public System.Comparison<uint> System_Comparison_uint(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Comparison<uint> fn = delegate(uint param0, uint param1) { return 0; };
			return fn;
		}

		if(!flag)
		{
			System_Comparison_uint_Event target = new System_Comparison_uint_Event(func);
			System.Comparison<uint> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Comparison_uint_Event target = new System_Comparison_uint_Event(func, self);
			System.Comparison<uint> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Comparison_uint(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(System.Comparison<uint>), L, pos);
	}

	void Push_System_Comparison_uint(IntPtr L, System.Comparison<uint> o)
	{
		ToLua.Push(L, o);
	}

	class System_Predicate_UnityEngine_EventSystems_EventTrigger_Entry_Event : LuaDelegate
	{
		public System_Predicate_UnityEngine_EventSystems_EventTrigger_Entry_Event(LuaFunction func) : base(func) { }
		public System_Predicate_UnityEngine_EventSystems_EventTrigger_Entry_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public bool Call(UnityEngine.EventSystems.EventTrigger.Entry param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}

		public bool CallWithSelf(UnityEngine.EventSystems.EventTrigger.Entry param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}
	}

	public System.Predicate<UnityEngine.EventSystems.EventTrigger.Entry> System_Predicate_UnityEngine_EventSystems_EventTrigger_Entry(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Predicate<UnityEngine.EventSystems.EventTrigger.Entry> fn = delegate(UnityEngine.EventSystems.EventTrigger.Entry param0) { return false; };
			return fn;
		}

		if(!flag)
		{
			System_Predicate_UnityEngine_EventSystems_EventTrigger_Entry_Event target = new System_Predicate_UnityEngine_EventSystems_EventTrigger_Entry_Event(func);
			System.Predicate<UnityEngine.EventSystems.EventTrigger.Entry> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Predicate_UnityEngine_EventSystems_EventTrigger_Entry_Event target = new System_Predicate_UnityEngine_EventSystems_EventTrigger_Entry_Event(func, self);
			System.Predicate<UnityEngine.EventSystems.EventTrigger.Entry> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Predicate_UnityEngine_EventSystems_EventTrigger_Entry(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(System.Predicate<UnityEngine.EventSystems.EventTrigger.Entry>), L, pos);
	}

	void Push_System_Predicate_UnityEngine_EventSystems_EventTrigger_Entry(IntPtr L, System.Predicate<UnityEngine.EventSystems.EventTrigger.Entry> o)
	{
		ToLua.Push(L, o);
	}

	class System_Action_UnityEngine_EventSystems_EventTrigger_Entry_Event : LuaDelegate
	{
		public System_Action_UnityEngine_EventSystems_EventTrigger_Entry_Event(LuaFunction func) : base(func) { }
		public System_Action_UnityEngine_EventSystems_EventTrigger_Entry_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.EventSystems.EventTrigger.Entry param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.EventSystems.EventTrigger.Entry param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public System.Action<UnityEngine.EventSystems.EventTrigger.Entry> System_Action_UnityEngine_EventSystems_EventTrigger_Entry(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<UnityEngine.EventSystems.EventTrigger.Entry> fn = delegate(UnityEngine.EventSystems.EventTrigger.Entry param0) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_UnityEngine_EventSystems_EventTrigger_Entry_Event target = new System_Action_UnityEngine_EventSystems_EventTrigger_Entry_Event(func);
			System.Action<UnityEngine.EventSystems.EventTrigger.Entry> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_UnityEngine_EventSystems_EventTrigger_Entry_Event target = new System_Action_UnityEngine_EventSystems_EventTrigger_Entry_Event(func, self);
			System.Action<UnityEngine.EventSystems.EventTrigger.Entry> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Action_UnityEngine_EventSystems_EventTrigger_Entry(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(System.Action<UnityEngine.EventSystems.EventTrigger.Entry>), L, pos);
	}

	void Push_System_Action_UnityEngine_EventSystems_EventTrigger_Entry(IntPtr L, System.Action<UnityEngine.EventSystems.EventTrigger.Entry> o)
	{
		ToLua.Push(L, o);
	}

	class System_Comparison_UnityEngine_EventSystems_EventTrigger_Entry_Event : LuaDelegate
	{
		public System_Comparison_UnityEngine_EventSystems_EventTrigger_Entry_Event(LuaFunction func) : base(func) { }
		public System_Comparison_UnityEngine_EventSystems_EventTrigger_Entry_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public int Call(UnityEngine.EventSystems.EventTrigger.Entry param0, UnityEngine.EventSystems.EventTrigger.Entry param1)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PushObject(param1);
			func.PCall();
			int ret = (int)func.CheckNumber();
			func.EndPCall();
			return ret;
		}

		public int CallWithSelf(UnityEngine.EventSystems.EventTrigger.Entry param0, UnityEngine.EventSystems.EventTrigger.Entry param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PushObject(param1);
			func.PCall();
			int ret = (int)func.CheckNumber();
			func.EndPCall();
			return ret;
		}
	}

	public System.Comparison<UnityEngine.EventSystems.EventTrigger.Entry> System_Comparison_UnityEngine_EventSystems_EventTrigger_Entry(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Comparison<UnityEngine.EventSystems.EventTrigger.Entry> fn = delegate(UnityEngine.EventSystems.EventTrigger.Entry param0, UnityEngine.EventSystems.EventTrigger.Entry param1) { return 0; };
			return fn;
		}

		if(!flag)
		{
			System_Comparison_UnityEngine_EventSystems_EventTrigger_Entry_Event target = new System_Comparison_UnityEngine_EventSystems_EventTrigger_Entry_Event(func);
			System.Comparison<UnityEngine.EventSystems.EventTrigger.Entry> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Comparison_UnityEngine_EventSystems_EventTrigger_Entry_Event target = new System_Comparison_UnityEngine_EventSystems_EventTrigger_Entry_Event(func, self);
			System.Comparison<UnityEngine.EventSystems.EventTrigger.Entry> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Comparison_UnityEngine_EventSystems_EventTrigger_Entry(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(System.Comparison<UnityEngine.EventSystems.EventTrigger.Entry>), L, pos);
	}

	void Push_System_Comparison_UnityEngine_EventSystems_EventTrigger_Entry(IntPtr L, System.Comparison<UnityEngine.EventSystems.EventTrigger.Entry> o)
	{
		ToLua.Push(L, o);
	}

	class UnityEngine_Events_UnityAction_UnityEngine_EventSystems_BaseEventData_Event : LuaDelegate
	{
		public UnityEngine_Events_UnityAction_UnityEngine_EventSystems_BaseEventData_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Events_UnityAction_UnityEngine_EventSystems_BaseEventData_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.EventSystems.BaseEventData param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.EventSystems.BaseEventData param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public UnityEngine.Events.UnityAction<UnityEngine.EventSystems.BaseEventData> UnityEngine_Events_UnityAction_UnityEngine_EventSystems_BaseEventData(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Events.UnityAction<UnityEngine.EventSystems.BaseEventData> fn = delegate(UnityEngine.EventSystems.BaseEventData param0) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Events_UnityAction_UnityEngine_EventSystems_BaseEventData_Event target = new UnityEngine_Events_UnityAction_UnityEngine_EventSystems_BaseEventData_Event(func);
			UnityEngine.Events.UnityAction<UnityEngine.EventSystems.BaseEventData> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Events_UnityAction_UnityEngine_EventSystems_BaseEventData_Event target = new UnityEngine_Events_UnityAction_UnityEngine_EventSystems_BaseEventData_Event(func, self);
			UnityEngine.Events.UnityAction<UnityEngine.EventSystems.BaseEventData> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_UnityEngine_Events_UnityAction_UnityEngine_EventSystems_BaseEventData(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(UnityEngine.Events.UnityAction<UnityEngine.EventSystems.BaseEventData>), L, pos);
	}

	void Push_UnityEngine_Events_UnityAction_UnityEngine_EventSystems_BaseEventData(IntPtr L, UnityEngine.Events.UnityAction<UnityEngine.EventSystems.BaseEventData> o)
	{
		ToLua.Push(L, o);
	}

	class UnityEngine_RectTransform_ReapplyDrivenProperties_Event : LuaDelegate
	{
		public UnityEngine_RectTransform_ReapplyDrivenProperties_Event(LuaFunction func) : base(func) { }
		public UnityEngine_RectTransform_ReapplyDrivenProperties_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.RectTransform param0)
		{
			func.BeginPCall();
			func.PushSealed(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.RectTransform param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushSealed(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public UnityEngine.RectTransform.ReapplyDrivenProperties UnityEngine_RectTransform_ReapplyDrivenProperties(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.RectTransform.ReapplyDrivenProperties fn = delegate(UnityEngine.RectTransform param0) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_RectTransform_ReapplyDrivenProperties_Event target = new UnityEngine_RectTransform_ReapplyDrivenProperties_Event(func);
			UnityEngine.RectTransform.ReapplyDrivenProperties d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_RectTransform_ReapplyDrivenProperties_Event target = new UnityEngine_RectTransform_ReapplyDrivenProperties_Event(func, self);
			UnityEngine.RectTransform.ReapplyDrivenProperties d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_UnityEngine_RectTransform_ReapplyDrivenProperties(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(UnityEngine.RectTransform.ReapplyDrivenProperties), L, pos);
	}

	void Push_UnityEngine_RectTransform_ReapplyDrivenProperties(IntPtr L, UnityEngine.RectTransform.ReapplyDrivenProperties o)
	{
		ToLua.Push(L, o);
	}

	class UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode_Event : LuaDelegate
	{
		public UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.SceneManagement.Scene param0, UnityEngine.SceneManagement.LoadSceneMode param1)
		{
			func.BeginPCall();
			func.PushValue(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.SceneManagement.Scene param0, UnityEngine.SceneManagement.LoadSceneMode param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushValue(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.LoadSceneMode> UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.LoadSceneMode> fn = delegate(UnityEngine.SceneManagement.Scene param0, UnityEngine.SceneManagement.LoadSceneMode param1) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode_Event target = new UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode_Event(func);
			UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.LoadSceneMode> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode_Event target = new UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode_Event(func, self);
			UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.LoadSceneMode> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.LoadSceneMode>), L, pos);
	}

	void Push_UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_LoadSceneMode(IntPtr L, UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.LoadSceneMode> o)
	{
		ToLua.Push(L, o);
	}

	class UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_Event : LuaDelegate
	{
		public UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.SceneManagement.Scene param0)
		{
			func.BeginPCall();
			func.PushValue(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.SceneManagement.Scene param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushValue(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene> UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene> fn = delegate(UnityEngine.SceneManagement.Scene param0) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_Event target = new UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_Event(func);
			UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_Event target = new UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_Event(func, self);
			UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene>), L, pos);
	}

	void Push_UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene(IntPtr L, UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene> o)
	{
		ToLua.Push(L, o);
	}

	class UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene_Event : LuaDelegate
	{
		public UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.SceneManagement.Scene param0, UnityEngine.SceneManagement.Scene param1)
		{
			func.BeginPCall();
			func.PushValue(param0);
			func.PushValue(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.SceneManagement.Scene param0, UnityEngine.SceneManagement.Scene param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushValue(param0);
			func.PushValue(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.Scene> UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.Scene> fn = delegate(UnityEngine.SceneManagement.Scene param0, UnityEngine.SceneManagement.Scene param1) { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene_Event target = new UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene_Event(func);
			UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.Scene> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene_Event target = new UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene_Event(func, self);
			UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.Scene> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.Scene>), L, pos);
	}

	void Push_UnityEngine_Events_UnityAction_UnityEngine_SceneManagement_Scene_UnityEngine_SceneManagement_Scene(IntPtr L, UnityEngine.Events.UnityAction<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.Scene> o)
	{
		ToLua.Push(L, o);
	}

	class UnityEngine_Canvas_WillRenderCanvases_Event : LuaDelegate
	{
		public UnityEngine_Canvas_WillRenderCanvases_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Canvas_WillRenderCanvases_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public UnityEngine.Canvas.WillRenderCanvases UnityEngine_Canvas_WillRenderCanvases(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Canvas.WillRenderCanvases fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Canvas_WillRenderCanvases_Event target = new UnityEngine_Canvas_WillRenderCanvases_Event(func);
			UnityEngine.Canvas.WillRenderCanvases d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Canvas_WillRenderCanvases_Event target = new UnityEngine_Canvas_WillRenderCanvases_Event(func, self);
			UnityEngine.Canvas.WillRenderCanvases d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_UnityEngine_Canvas_WillRenderCanvases(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(UnityEngine.Canvas.WillRenderCanvases), L, pos);
	}

	void Push_UnityEngine_Canvas_WillRenderCanvases(IntPtr L, UnityEngine.Canvas.WillRenderCanvases o)
	{
		ToLua.Push(L, o);
	}

	class OnServerConnect_Event : LuaDelegate
	{
		public OnServerConnect_Event(LuaFunction func) : base(func) { }
		public OnServerConnect_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(int param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(int param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public OnServerConnect OnServerConnect(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			OnServerConnect fn = delegate(int param0) { };
			return fn;
		}

		if(!flag)
		{
			OnServerConnect_Event target = new OnServerConnect_Event(func);
			OnServerConnect d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			OnServerConnect_Event target = new OnServerConnect_Event(func, self);
			OnServerConnect d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_OnServerConnect(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(OnServerConnect), L, pos);
	}

	void Push_OnServerConnect(IntPtr L, OnServerConnect o)
	{
		ToLua.Push(L, o);
	}

	class OnServerCloseConnect_Event : LuaDelegate
	{
		public OnServerCloseConnect_Event(LuaFunction func) : base(func) { }
		public OnServerCloseConnect_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public OnServerCloseConnect OnServerCloseConnect(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			OnServerCloseConnect fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			OnServerCloseConnect_Event target = new OnServerCloseConnect_Event(func);
			OnServerCloseConnect d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			OnServerCloseConnect_Event target = new OnServerCloseConnect_Event(func, self);
			OnServerCloseConnect d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_OnServerCloseConnect(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(OnServerCloseConnect), L, pos);
	}

	void Push_OnServerCloseConnect(IntPtr L, OnServerCloseConnect o)
	{
		ToLua.Push(L, o);
	}

	class OnServerMessage_Event : LuaDelegate
	{
		public OnServerMessage_Event(LuaFunction func) : base(func) { }
		public OnServerMessage_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(ByteBuffer param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(ByteBuffer param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public OnServerMessage OnServerMessage(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			OnServerMessage fn = delegate(ByteBuffer param0) { };
			return fn;
		}

		if(!flag)
		{
			OnServerMessage_Event target = new OnServerMessage_Event(func);
			OnServerMessage d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			OnServerMessage_Event target = new OnServerMessage_Event(func, self);
			OnServerMessage d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_OnServerMessage(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(OnServerMessage), L, pos);
	}

	void Push_OnServerMessage(IntPtr L, OnServerMessage o)
	{
		ToLua.Push(L, o);
	}

	class OnHeroStarMove_Event : LuaDelegate
	{
		public OnHeroStarMove_Event(LuaFunction func) : base(func) { }
		public OnHeroStarMove_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(float param0, float param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(float param0, float param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public OnHeroStarMove OnHeroStarMove(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			OnHeroStarMove fn = delegate(float param0, float param1) { };
			return fn;
		}

		if(!flag)
		{
			OnHeroStarMove_Event target = new OnHeroStarMove_Event(func);
			OnHeroStarMove d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			OnHeroStarMove_Event target = new OnHeroStarMove_Event(func, self);
			OnHeroStarMove d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_OnHeroStarMove(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(OnHeroStarMove), L, pos);
	}

	void Push_OnHeroStarMove(IntPtr L, OnHeroStarMove o)
	{
		ToLua.Push(L, o);
	}

	class OnHeroEndMove_Event : LuaDelegate
	{
		public OnHeroEndMove_Event(LuaFunction func) : base(func) { }
		public OnHeroEndMove_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public OnHeroEndMove OnHeroEndMove(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			OnHeroEndMove fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			OnHeroEndMove_Event target = new OnHeroEndMove_Event(func);
			OnHeroEndMove d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			OnHeroEndMove_Event target = new OnHeroEndMove_Event(func, self);
			OnHeroEndMove d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_OnHeroEndMove(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(OnHeroEndMove), L, pos);
	}

	void Push_OnHeroEndMove(IntPtr L, OnHeroEndMove o)
	{
		ToLua.Push(L, o);
	}

	class OnHeroMoveIng_Event : LuaDelegate
	{
		public OnHeroMoveIng_Event(LuaFunction func) : base(func) { }
		public OnHeroMoveIng_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public OnHeroMoveIng OnHeroMoveIng(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			OnHeroMoveIng fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			OnHeroMoveIng_Event target = new OnHeroMoveIng_Event(func);
			OnHeroMoveIng d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			OnHeroMoveIng_Event target = new OnHeroMoveIng_Event(func, self);
			OnHeroMoveIng d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_OnHeroMoveIng(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(OnHeroMoveIng), L, pos);
	}

	void Push_OnHeroMoveIng(IntPtr L, OnHeroMoveIng o)
	{
		ToLua.Push(L, o);
	}

	class OnHeroClickEntity_Event : LuaDelegate
	{
		public OnHeroClickEntity_Event(LuaFunction func) : base(func) { }
		public OnHeroClickEntity_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(CRoleSprite param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(CRoleSprite param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public OnHeroClickEntity OnHeroClickEntity(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			OnHeroClickEntity fn = delegate(CRoleSprite param0) { };
			return fn;
		}

		if(!flag)
		{
			OnHeroClickEntity_Event target = new OnHeroClickEntity_Event(func);
			OnHeroClickEntity d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			OnHeroClickEntity_Event target = new OnHeroClickEntity_Event(func, self);
			OnHeroClickEntity d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_OnHeroClickEntity(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(OnHeroClickEntity), L, pos);
	}

	void Push_OnHeroClickEntity(IntPtr L, OnHeroClickEntity o)
	{
		ToLua.Push(L, o);
	}

	class OnHeroClickGround_Event : LuaDelegate
	{
		public OnHeroClickGround_Event(LuaFunction func) : base(func) { }
		public OnHeroClickGround_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.Vector3 param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.Vector3 param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public OnHeroClickGround OnHeroClickGround(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			OnHeroClickGround fn = delegate(UnityEngine.Vector3 param0) { };
			return fn;
		}

		if(!flag)
		{
			OnHeroClickGround_Event target = new OnHeroClickGround_Event(func);
			OnHeroClickGround d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			OnHeroClickGround_Event target = new OnHeroClickGround_Event(func, self);
			OnHeroClickGround d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_OnHeroClickGround(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(OnHeroClickGround), L, pos);
	}

	void Push_OnHeroClickGround(IntPtr L, OnHeroClickGround o)
	{
		ToLua.Push(L, o);
	}

	class OnAttackKeyFrame_Event : LuaDelegate
	{
		public OnAttackKeyFrame_Event(LuaFunction func) : base(func) { }
		public OnAttackKeyFrame_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(CBattleRole param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(CBattleRole param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public OnAttackKeyFrame OnAttackKeyFrame(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			OnAttackKeyFrame fn = delegate(CBattleRole param0) { };
			return fn;
		}

		if(!flag)
		{
			OnAttackKeyFrame_Event target = new OnAttackKeyFrame_Event(func);
			OnAttackKeyFrame d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			OnAttackKeyFrame_Event target = new OnAttackKeyFrame_Event(func, self);
			OnAttackKeyFrame d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_OnAttackKeyFrame(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(OnAttackKeyFrame), L, pos);
	}

	void Push_OnAttackKeyFrame(IntPtr L, OnAttackKeyFrame o)
	{
		ToLua.Push(L, o);
	}

	class OnAttackEnd_Event : LuaDelegate
	{
		public OnAttackEnd_Event(LuaFunction func) : base(func) { }
		public OnAttackEnd_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(CBattleRole param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(CBattleRole param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public OnAttackEnd OnAttackEnd(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			OnAttackEnd fn = delegate(CBattleRole param0) { };
			return fn;
		}

		if(!flag)
		{
			OnAttackEnd_Event target = new OnAttackEnd_Event(func);
			OnAttackEnd d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			OnAttackEnd_Event target = new OnAttackEnd_Event(func, self);
			OnAttackEnd d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_OnAttackEnd(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(OnAttackEnd), L, pos);
	}

	void Push_OnAttackEnd(IntPtr L, OnAttackEnd o)
	{
		ToLua.Push(L, o);
	}

	class OnBeatKeyFrame_Event : LuaDelegate
	{
		public OnBeatKeyFrame_Event(LuaFunction func) : base(func) { }
		public OnBeatKeyFrame_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(CBattleRole param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(CBattleRole param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public OnBeatKeyFrame OnBeatKeyFrame(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			OnBeatKeyFrame fn = delegate(CBattleRole param0) { };
			return fn;
		}

		if(!flag)
		{
			OnBeatKeyFrame_Event target = new OnBeatKeyFrame_Event(func);
			OnBeatKeyFrame d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			OnBeatKeyFrame_Event target = new OnBeatKeyFrame_Event(func, self);
			OnBeatKeyFrame d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_OnBeatKeyFrame(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(OnBeatKeyFrame), L, pos);
	}

	void Push_OnBeatKeyFrame(IntPtr L, OnBeatKeyFrame o)
	{
		ToLua.Push(L, o);
	}

	class OnBeatEnd_Event : LuaDelegate
	{
		public OnBeatEnd_Event(LuaFunction func) : base(func) { }
		public OnBeatEnd_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(CBattleRole param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(CBattleRole param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public OnBeatEnd OnBeatEnd(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			OnBeatEnd fn = delegate(CBattleRole param0) { };
			return fn;
		}

		if(!flag)
		{
			OnBeatEnd_Event target = new OnBeatEnd_Event(func);
			OnBeatEnd d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			OnBeatEnd_Event target = new OnBeatEnd_Event(func, self);
			OnBeatEnd d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_OnBeatEnd(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(OnBeatEnd), L, pos);
	}

	void Push_OnBeatEnd(IntPtr L, OnBeatEnd o)
	{
		ToLua.Push(L, o);
	}

	class OnDeadEnd_Event : LuaDelegate
	{
		public OnDeadEnd_Event(LuaFunction func) : base(func) { }
		public OnDeadEnd_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(CBattleRole param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(CBattleRole param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public OnDeadEnd OnDeadEnd(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			OnDeadEnd fn = delegate(CBattleRole param0) { };
			return fn;
		}

		if(!flag)
		{
			OnDeadEnd_Event target = new OnDeadEnd_Event(func);
			OnDeadEnd d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			OnDeadEnd_Event target = new OnDeadEnd_Event(func, self);
			OnDeadEnd d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_OnDeadEnd(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(OnDeadEnd), L, pos);
	}

	void Push_OnDeadEnd(IntPtr L, OnDeadEnd o)
	{
		ToLua.Push(L, o);
	}

	class OnMoveTargetCallBack_Event : LuaDelegate
	{
		public OnMoveTargetCallBack_Event(LuaFunction func) : base(func) { }
		public OnMoveTargetCallBack_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(CBattleRole param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(CBattleRole param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public OnMoveTargetCallBack OnMoveTargetCallBack(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			OnMoveTargetCallBack fn = delegate(CBattleRole param0) { };
			return fn;
		}

		if(!flag)
		{
			OnMoveTargetCallBack_Event target = new OnMoveTargetCallBack_Event(func);
			OnMoveTargetCallBack d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			OnMoveTargetCallBack_Event target = new OnMoveTargetCallBack_Event(func, self);
			OnMoveTargetCallBack d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_OnMoveTargetCallBack(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(OnMoveTargetCallBack), L, pos);
	}

	void Push_OnMoveTargetCallBack(IntPtr L, OnMoveTargetCallBack o)
	{
		ToLua.Push(L, o);
	}

	class OnSkillEnd_Event : LuaDelegate
	{
		public OnSkillEnd_Event(LuaFunction func) : base(func) { }
		public OnSkillEnd_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(object param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(object param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public OnSkillEnd OnSkillEnd(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			OnSkillEnd fn = delegate(object param0) { };
			return fn;
		}

		if(!flag)
		{
			OnSkillEnd_Event target = new OnSkillEnd_Event(func);
			OnSkillEnd d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			OnSkillEnd_Event target = new OnSkillEnd_Event(func, self);
			OnSkillEnd d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_OnSkillEnd(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(OnSkillEnd), L, pos);
	}

	void Push_OnSkillEnd(IntPtr L, OnSkillEnd o)
	{
		ToLua.Push(L, o);
	}

	class OnSkillKeyFrame_Event : LuaDelegate
	{
		public OnSkillKeyFrame_Event(LuaFunction func) : base(func) { }
		public OnSkillKeyFrame_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(CSkillSprite param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(CSkillSprite param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public OnSkillKeyFrame OnSkillKeyFrame(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			OnSkillKeyFrame fn = delegate(CSkillSprite param0) { };
			return fn;
		}

		if(!flag)
		{
			OnSkillKeyFrame_Event target = new OnSkillKeyFrame_Event(func);
			OnSkillKeyFrame d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			OnSkillKeyFrame_Event target = new OnSkillKeyFrame_Event(func, self);
			OnSkillKeyFrame d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_OnSkillKeyFrame(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(OnSkillKeyFrame), L, pos);
	}

	void Push_OnSkillKeyFrame(IntPtr L, OnSkillKeyFrame o)
	{
		ToLua.Push(L, o);
	}

	class OnSkillTriggerHitEffect_Event : LuaDelegate
	{
		public OnSkillTriggerHitEffect_Event(LuaFunction func) : base(func) { }
		public OnSkillTriggerHitEffect_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(string param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(string param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public OnSkillTriggerHitEffect OnSkillTriggerHitEffect(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			OnSkillTriggerHitEffect fn = delegate(string param0) { };
			return fn;
		}

		if(!flag)
		{
			OnSkillTriggerHitEffect_Event target = new OnSkillTriggerHitEffect_Event(func);
			OnSkillTriggerHitEffect d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			OnSkillTriggerHitEffect_Event target = new OnSkillTriggerHitEffect_Event(func, self);
			OnSkillTriggerHitEffect d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_OnSkillTriggerHitEffect(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(OnSkillTriggerHitEffect), L, pos);
	}

	void Push_OnSkillTriggerHitEffect(IntPtr L, OnSkillTriggerHitEffect o)
	{
		ToLua.Push(L, o);
	}

	class System_Action_UnityEngine_Object_Event : LuaDelegate
	{
		public System_Action_UnityEngine_Object_Event(LuaFunction func) : base(func) { }
		public System_Action_UnityEngine_Object_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.Object param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.Object param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public System.Action<UnityEngine.Object> System_Action_UnityEngine_Object(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<UnityEngine.Object> fn = delegate(UnityEngine.Object param0) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_UnityEngine_Object_Event target = new System_Action_UnityEngine_Object_Event(func);
			System.Action<UnityEngine.Object> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_UnityEngine_Object_Event target = new System_Action_UnityEngine_Object_Event(func, self);
			System.Action<UnityEngine.Object> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Action_UnityEngine_Object(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(System.Action<UnityEngine.Object>), L, pos);
	}

	void Push_System_Action_UnityEngine_Object(IntPtr L, System.Action<UnityEngine.Object> o)
	{
		ToLua.Push(L, o);
	}

	class OnDragBegin_Event : LuaDelegate
	{
		public OnDragBegin_Event(LuaFunction func) : base(func) { }
		public OnDragBegin_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public OnDragBegin OnDragBegin(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			OnDragBegin fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			OnDragBegin_Event target = new OnDragBegin_Event(func);
			OnDragBegin d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			OnDragBegin_Event target = new OnDragBegin_Event(func, self);
			OnDragBegin d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_OnDragBegin(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(OnDragBegin), L, pos);
	}

	void Push_OnDragBegin(IntPtr L, OnDragBegin o)
	{
		ToLua.Push(L, o);
	}

	class OnDrag_Event : LuaDelegate
	{
		public OnDrag_Event(LuaFunction func) : base(func) { }
		public OnDrag_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public OnDrag OnDrag(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			OnDrag fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			OnDrag_Event target = new OnDrag_Event(func);
			OnDrag d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			OnDrag_Event target = new OnDrag_Event(func, self);
			OnDrag d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_OnDrag(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(OnDrag), L, pos);
	}

	void Push_OnDrag(IntPtr L, OnDrag o)
	{
		ToLua.Push(L, o);
	}

	class OnDragEnd_Event : LuaDelegate
	{
		public OnDragEnd_Event(LuaFunction func) : base(func) { }
		public OnDragEnd_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public OnDragEnd OnDragEnd(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			OnDragEnd fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			OnDragEnd_Event target = new OnDragEnd_Event(func);
			OnDragEnd d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			OnDragEnd_Event target = new OnDragEnd_Event(func, self);
			OnDragEnd d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_OnDragEnd(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(OnDragEnd), L, pos);
	}

	void Push_OnDragEnd(IntPtr L, OnDragEnd o)
	{
		ToLua.Push(L, o);
	}

	class OnFuncCallBackDelegate_Event : LuaDelegate
	{
		public OnFuncCallBackDelegate_Event(LuaFunction func) : base(func) { }
		public OnFuncCallBackDelegate_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(string param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(string param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public OnFuncCallBackDelegate OnFuncCallBackDelegate(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			OnFuncCallBackDelegate fn = delegate(string param0) { };
			return fn;
		}

		if(!flag)
		{
			OnFuncCallBackDelegate_Event target = new OnFuncCallBackDelegate_Event(func);
			OnFuncCallBackDelegate d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			OnFuncCallBackDelegate_Event target = new OnFuncCallBackDelegate_Event(func, self);
			OnFuncCallBackDelegate d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_OnFuncCallBackDelegate(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(OnFuncCallBackDelegate), L, pos);
	}

	void Push_OnFuncCallBackDelegate(IntPtr L, OnFuncCallBackDelegate o)
	{
		ToLua.Push(L, o);
	}

}

