//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class EmDirectionWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(EmDirection));
		L.RegVar("emDirectionLeft", get_emDirectionLeft, null);
		L.RegVar("emDirectionRight", get_emDirectionRight, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<EmDirection>.Check = CheckType;
		StackTraits<EmDirection>.Push = Push;
	}

	static void Push(IntPtr L, EmDirection arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(EmDirection), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_emDirectionLeft(IntPtr L)
	{
		ToLua.Push(L, EmDirection.emDirectionLeft);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_emDirectionRight(IntPtr L)
	{
		ToLua.Push(L, EmDirection.emDirectionRight);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		EmDirection o = (EmDirection)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

