//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ScrollRectExtendWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ScrollRectExtend), typeof(UnityEngine.UI.ScrollRect));
		L.RegFunction("OnBeginDrag", OnBeginDrag);
		L.RegFunction("OnDrag", OnDrag);
		L.RegFunction("OnEndDrag", OnEndDrag);
		L.RegFunction("SetDragBeginCallBack", SetDragBeginCallBack);
		L.RegFunction("SetDragCallBack", SetDragCallBack);
		L.RegFunction("SetDragEndCallBack", SetDragEndCallBack);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnBeginDrag(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ScrollRectExtend obj = (ScrollRectExtend)ToLua.CheckObject<ScrollRectExtend>(L, 1);
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject<UnityEngine.EventSystems.PointerEventData>(L, 2);
			obj.OnBeginDrag(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnDrag(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ScrollRectExtend obj = (ScrollRectExtend)ToLua.CheckObject<ScrollRectExtend>(L, 1);
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject<UnityEngine.EventSystems.PointerEventData>(L, 2);
			obj.OnDrag(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnEndDrag(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ScrollRectExtend obj = (ScrollRectExtend)ToLua.CheckObject<ScrollRectExtend>(L, 1);
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject<UnityEngine.EventSystems.PointerEventData>(L, 2);
			obj.OnEndDrag(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetDragBeginCallBack(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ScrollRectExtend obj = (ScrollRectExtend)ToLua.CheckObject<ScrollRectExtend>(L, 1);
			OnDragBegin arg0 = (OnDragBegin)ToLua.CheckDelegate<OnDragBegin>(L, 2);
			obj.SetDragBeginCallBack(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetDragCallBack(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ScrollRectExtend obj = (ScrollRectExtend)ToLua.CheckObject<ScrollRectExtend>(L, 1);
			OnDrag arg0 = (OnDrag)ToLua.CheckDelegate<OnDrag>(L, 2);
			obj.SetDragCallBack(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetDragEndCallBack(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ScrollRectExtend obj = (ScrollRectExtend)ToLua.CheckObject<ScrollRectExtend>(L, 1);
			OnDragEnd arg0 = (OnDragEnd)ToLua.CheckDelegate<OnDragEnd>(L, 2);
			obj.SetDragEndCallBack(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

