---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/3/2 18:24
---
LuaCUIUpdate = {};

local this = LuaCUIUpdate;

local m_gameObject = nil;
local m_txtSpeed = nil;     --下载速度
local m_txtProgress = nil;  --下载进度
local m_proRectTransform = nil;
local m_progressSlider = nil;
local m_fProgressWidth = 0;

function LuaCUIUpdate.Awake(gameObject)
    if (gameObject == nil) then
        return;
    end
    m_gameObject = gameObject;

    local txtContentTsm = m_gameObject.transform:FindChild("txtContent");
    if(txtContentTsm ~= nil) then
        local txtContent = txtContentTsm:GetComponent("Text");
        if (txtContent ~= nil) then
            txtContent.text = LuaCUpdate.GetLanguageText("Update_Tips");
        end
    end

    local txtSpeedTsm = m_gameObject.transform:FindChild("txtSpeed");
    if(txtSpeedTsm ~= nil) then
        m_txtSpeed = txtSpeedTsm:GetComponent("Text");
        if (m_txtSpeed ~= nil) then
            m_txtSpeed.text = "0KB/s";
        end
    end

    local txtProgressTsm = m_gameObject.transform:FindChild("txtProgress");
    if(txtProgressTsm ~= nil) then
        m_txtProgress = txtProgressTsm:GetComponent("Text");
    end

    local maskTsm = m_gameObject.transform:FindChild("progress/ImageMask");
    if(maskTsm ~= nil) then
        m_proRectTransform = maskTsm:GetComponent("RectTransform");
        m_fProgressWidth = m_proRectTransform.sizeDelta.x;
    end
    local sliderTsm = m_gameObject.transform:FindChild("progress/imgSlider");
    if(sliderTsm ~= nil) then
        m_progressSlider = sliderTsm:GetComponent("RectTransform");
    end
end

function LuaCUIUpdate.Start()
    if (m_gameObject == nil) then
        return;
    end

    this.UpdateProgressBar(0);
end

function LuaCUIUpdate.ShowUI()
    if(m_gameObject ~= nil and m_gameObject.activeSelf) then
        return;
    end
    if(m_gameObject == nil) then
        local prefabObj = CAssetManager.GetAsset("Prefabs/UI/UIUpdate.prefab");
        if(prefabObj == nil) then
            return;
        end
        m_gameObject = UnityEngine.GameObject.Instantiate(prefabObj)
        if(m_gameObject == nil) then
            log("创建预设失败: Prefabs/UI/UIUpdate")
            return
        end
        local uiCanvas = UnityEngine.GameObject.Find("topCanvas")
        if(uiCanvas ~= nil) then
            m_gameObject.transform:SetParent(uiCanvas.transform, false);
        end
    else
        m_gameObject:SetActive(true);
        m_gameObject.transform:SetAsLastSibling();
    end
end

function LuaCUIUpdate.HideUI()
    if (m_gameObject == nil or m_gameObject.activeSelf == false) then
        return;
    end
    m_gameObject:SetActive(false);
end

--刷新下载速度
function LuaCUIUpdate.UpdateSpeed(strSpeed)
    if(m_txtSpeed ~= nil) then
        m_txtSpeed.text = strSpeed;
    end
end

--刷新进度条
function LuaCUIUpdate.UpdateProgressBar(fPercent)
    if (m_txtProgress ~= nil) then
        m_txtProgress.text = math.floor(fPercent * 100) .. "%";
    end

    local fSliderX = 0;
    if (m_proRectTransform ~= nil) then
        m_proRectTransform.sizeDelta = UnityEngine.Vector2.New(fPercent * m_fProgressWidth, m_proRectTransform.rect.height);
        fSliderX = fPercent * m_fProgressWidth;
    end

    if (m_progressSlider ~= nil) then
        m_progressSlider.anchoredPosition = UnityEngine.Vector2.New(fSliderX, m_progressSlider.anchoredPosition.y);
    end
end

-- 界面显示状态
function LuaCUIUpdate.GetVisible()
    if(m_gameObject == nil) then
        return false;
    else
        return m_gameObject.activeSelf;
    end
end