---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/3/2 19:18
---
LuaCUIUpdateConfirm = {};

local this = LuaCUIUpdateConfirm;

local m_gameObject = nil;
local m_txtContent = nil;  --提示内容文本
local m_txtAdvise = nil;   --建议文本
local m_btnSure = nil;     --确认按钮
local m_btnCancel = nil;   --取消按钮
local m_sureFunc = nil;    --确认函数
local m_cancelFunc = nil;  --取消函数

function LuaCUIUpdateConfirm.Awake(gameObject)
    if (gameObject == nil) then
        return;
    end
    m_gameObject = gameObject;

    local txtContentTsm = m_gameObject.transform:FindChild("UIContainer/txt_content");
    if(txtContentTsm ~= nil) then
        m_txtContent = txtContentTsm:GetComponent("Text");
    end

    local txtAdviseTsm = m_gameObject.transform:FindChild("UIContainer/txtAdvise");
    if(txtAdviseTsm ~= nil) then
        m_txtAdvise = txtAdviseTsm:GetComponent("Text");
    end

    local btnTransform = m_gameObject.transform:FindChild("UIContainer/btn_cancel");
    if(btnTransform ~= nil) then
        m_btnCancel = btnTransform:GetComponent("Button");
        m_btnCancel.onClick:AddListener(this.OnClickCancel) ;
    end

    btnTransform = m_gameObject.transform:FindChild("UIContainer/btn_sure");
    if(btnTransform ~= nil) then
        m_btnSure = btnTransform:GetComponent("Button");
        m_btnSure.onClick:AddListener(this.OnClickSure) ;
    end
end

function LuaCUIUpdateConfirm.Start()
    if (m_gameObject == nil) then
        return;
    end
end

--点击确定
function LuaCUIUpdateConfirm.OnClickSure()
    if (m_sureFunc ~= nil) then
        m_sureFunc();
    end
    this.HideUI();
end

--点击取消
function LuaCUIUpdateConfirm.OnClickCancel()
    if (m_cancelFunc ~= nil) then
        m_cancelFunc();
    end
    this.HideUI();
end

--显示确认框
function LuaCUIUpdateConfirm.ShowConfirm(strContent, strAdvise, sureFunc, cancelFunc)
    this.ShowUI();
    if(m_txtContent ~= nil) then
        m_txtContent.text = strContent;
    end

    if(m_txtAdvise ~= nil) then
        m_txtAdvise.text = strAdvise;
    end

    m_sureFunc = sureFunc;
    m_cancelFunc = cancelFunc;
end

function LuaCUIUpdateConfirm.ShowUI()
    if(m_gameObject == nil) then
        local prefabObj = CAssetManager.GetAsset("Prefabs/UI/Update/UIUpdateConfirmPanel.prefab");
        if(prefabObj == nil) then
            return;
        end
        m_gameObject = UnityEngine.GameObject.Instantiate(prefabObj)
        if(m_gameObject == nil) then
            log("创建预设失败: Prefabs/UI/Update/UIUpdateConfirmPanel")
            return
        end
        local uiCanvas = UnityEngine.GameObject.Find("Canvas")
        if(uiCanvas ~= nil) then
            m_gameObject.transform:SetParent(uiCanvas.transform, false);
        end
    else

    end
    m_gameObject:SetActive(true);
    m_gameObject.transform:SetAsLastSibling();
end

function LuaCUIUpdateConfirm.HideUI()
    if (m_gameObject == nil or m_gameObject.activeSelf == false) then
        return;
    end
    m_gameObject:SetActive(false);
    m_sureFunc = nil;
    m_cancelFunc = nil;
end